# Generated by Django 5.0.6 on 2024-05-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_room_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='projectors',
            new_name='projector',
        ),
    ]
