# Generated by Django 5.0.6 on 2024-05-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_projectors_rooms_projector'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rooms')),
            ],
        ),
    ]
