# Generated by Django 5.0.6 on 2024-05-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_roomsreservation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomsreservation',
            unique_together={('date', 'room')},
        ),
    ]
